# Generated by Django 5.2.5 on 2025-08-05 13:28

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS booking",
            reverse_sql="DROP SCHEMA IF EXISTS booking CASCADE",
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "description",
                    models.TextField(blank=True, db_comment="Описание номера"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        db_comment="Стоимоть номера",
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="Время открытия номера для бронирования",
                    ),
                ),
            ],
            options={
                "db_table": 'booking"."room',
                "db_table_comment": "Номера в отелях",
            },
        ),
    ]
