# Generated by Django 5.2.5 on 2025-08-05 13:28

import django.db.models.deletion
from django.db import migrations, models

import booking.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE SCHEMA IF NOT EXISTS booking",
            reverse_sql="DROP SCHEMA IF EXISTS booking CASCADE",
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "date_start",
                    models.DateField(
                        db_comment="Дата заезда",
                        validators=[booking.models.validate_date_start],
                    ),
                ),
                ("date_end", models.DateField(db_comment="Дата выезда")),
                (
                    "room_id",
                    models.ForeignKey(
                        db_column="room_id",
                        db_comment="Ссылка на забронированный номер",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "db_table": 'booking"."booking',
                "db_table_comment": "Бронирования номеров отеля",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("date_end__gt", models.F("date_start"))),
                        name="booking_end_after_start",
                    )
                ],
            },
        ),
    ]
